### ISSUE TITLE
Readability: search box & command palette

### ISSUE THREAD

**Issue by rongmu** [simicd/jupyterlab-tailwind-theme#1]
Thank you for creating this beautiful theme!
I encountered two readability issues:

## Search box

The search box has transparent background; case and regex toggles are not shown.

<figure>
<img src="https://user-images.githubusercontent.com/1129506/71077210-59af6a00-21ca-11ea-920f-0efafde496eb.jpg" width="400px">
    <figcaption>Default</figcaption>
</figure>

***

<figure>
    <img src="https://user-images.githubusercontent.com/1129506/71077212-5a480080-21ca-11ea-8795-435087929e40.jpg"  width="380px">
    <figcaption>Tailwind</figcaption>
</figure>

## Command palette

Black-on-purple text is a bit difficult to read.

<figure>
    <img src="https://user-images.githubusercontent.com/1129506/71078884-96c92b80-21cd-11ea-97e2-034f3f8a99e3.jpg" width="250px"><figcaption>Default</figcaption>
</figure>

***

<figure>
    <img src="https://user-images.githubusercontent.com/1129506/71077211-5a480080-21ca-11ea-98d8-ffa44451891f.jpg" width="280px">
    <figcaption>Tailwind</figcaption>
</figure>

**Comment by simicd** [comment]
Thank you, I'm very glad to hear you like the theme!
I appreciate your feedback - looked at both issues you reported and made adjustments to the theme. Below a proposal - if you are fine with this I will publish it to npm.

- Search box:
![image](https://user-images.githubusercontent.com/10134699/71112900-d17e9400-21cc-11ea-9877-9222e019461f.png)

- Command palette:
![image](https://user-images.githubusercontent.com/10134699/71113005-fd9a1500-21cc-11ea-9332-06f6bec4b0a2.png)

**Comment by rongmu** [comment]
Thank you for the response.
The changes look great! I really appreciate your work.

**Comment by simicd** [comment]
Thank you - I merged the changes into master and published v0.3.1 to [npm](https://www.npmjs.com/package/jupyterlab-tailwind-theme). Have a great rest of the week!
