### ISSUE TITLE
Cursor left at last position even in command mode

### ISSUE THREAD

**Issue by ejisoo** [simicd/jupyterlab-tailwind-theme#15]
Hey Dejan,

Thanks for creating this beautiful theme. I really like the colors and the little details - including the centered cells.

I noticed a small glitch when using the theme with [jupyterlab-vim](https://github.com/axelfahy/jupyterlab-vim). I'm raising this here because it hasn't happened with other themes or the default themes.

You'll notice in the picture below that when you exit edit mode to command mode, the cursor stays at the last position, making me think that I'm still editing the cell. This often leads to deleting the whole cell by pressing D, D when I only need to delete the line. I would look for the blue cell bound indicating active, but the eye goes for the cursor first.

Is this something you can look into and help with? I'm attaching the list of extensions installed.
```
        @axlair/jupyterlab_vim v0.12.4  enabled  OK
        @deathbeds/jupyterlab-fonts v1.0.1  enabled  OK
        @jupyterlab/git v0.21.0-alpha.0 disabled OK
        @jupyterlab/toc v4.0.0  enabled  OK
        @mohirio/jupyterlab-horizon-theme v2.0.0  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.3.6  enabled  OK
        @wallneradam/custom_css v0.2.0  enabled  OK
        jupyterlab-tailwind-theme v0.4.2  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK
```

I really appreciate your time!

![theme](https://user-images.githubusercontent.com/7435407/91331502-d4d51100-e798-11ea-99d3-7ce9c11718d2.gif)

**Comment by simicd** [comment]
Hi Jisoo,

Highly appreciate your feedback, glad to hear you like the theme!

Thanks to your detailed description I was able to reproduce the issue. It goes back to an override
of the cursor blinking where the only way I found was to force the cursor to stay visible. 

```
.jp-mod-selected .CodeMirror-cursors {
  visibility: visible !important;
}
```

There is still no setting available to change the blinking rate but with a small tweak, the 
cursor is only forced to stay visible if the code cell is focused. 

```
.CodeMirror-focused .CodeMirror-cursors {
  visibility: visible !important;
}
```

Here the result (tried it with the vim extension as well):
![fix-cursor-issue](https://user-images.githubusercontent.com/10134699/91611146-eaa22c00-e97a-11ea-8e50-0a65b0259841.gif)

I just published [version 0.4.3](https://www.npmjs.com/package/jupyterlab-tailwind-theme) on npm, check it out and let me know if you still face issues.
