### ISSUE TITLE
Update to support lates Jupyterlab 3.x.x version

### ISSUE THREAD

**Issue by jaungiers** [simicd/jupyterlab-tailwind-theme#21]
Jupyterlab has been updated to version >3.0.0 (currently on 3.0.5). This extension is not supported on these versions and gives an error when trying to install it. Please update for latest Jupterlab version. Thank you.

**Comment by WestedCrean** [comment]
Hi @simicd 

Really love this theme so I ported it to Jupyterlab 3.x using migration instructions from https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html

Please check pull request here https://github.com/simicd/jupyterlab-tailwind-theme/pull/24

**Comment by simicd** [comment]
Hi @WestedCrean, wow thank you so much!! I'll test the PR and then merge it.

**Comment by simicd** [comment]
The package is now deployed to [npm as v3.0.0](https://www.npmjs.com/package/jupyterlab-tailwind-theme) - thanks again @WestedCrean!
