### ISSUE TITLE
Add themed scrollbars

### ISSUE THREAD

**Issue by gMatas** [simicd/jupyterlab-tailwind-theme#28]
Scroll bars, using dark theme, in particular, stands out from the rest of the theme.

**Comment by simicd** [comment]
Thanks @gMatas, found a way to make it work in both Chrome/Edge and Firefox, here are the results:
![image](https://user-images.githubusercontent.com/10134699/116789041-3595b580-aaad-11eb-9768-155974e464da.png)
![image](https://user-images.githubusercontent.com/10134699/116789042-39293c80-aaad-11eb-8379-e437648827c2.png)

**Comment by simicd** [comment]
Plan to release this tonight, let me know if you have any further suggestions!

**Comment by simicd** [comment]
Just released it [version 3.0.1](https://www.npmjs.com/package/jupyterlab-tailwind-theme) with the fix

**Comment by gMatas** [comment]
Looks really nice! However, I've noticed that not all scroll bars were affected as seen here:
![image](https://user-images.githubusercontent.com/26392564/116791828-8fa27500-aac5-11eb-9357-d4b406ba9e39.png)

**Comment by gMatas** [comment]
As for other similar suggestions, one that comes to mind is making dividers (white lines) not stand out as much from the rest of the theme as seen here 
![image](https://user-images.githubusercontent.com/26392564/116792130-78648700-aac7-11eb-937c-ce7699e84c96.png)

**Comment by simicd** [comment]
Thanks @gMatas! Incorporated the fix as well as the divider suggestion and released it to npm as [v3.0.2](https://www.npmjs.com/package/jupyterlab-tailwind-theme)
