### ISSUE TITLE
The Markdown Editor

### ISSUE THREAD

**Issue by skriptum** [simicd/jupyterlab-tailwind-theme#29]
Hi there,
first of all, thank you for the wonderful theme, it really makes jupyterlab feel like an IDE. 

Currently though, the editing mode for markdown files looks kinda like a terminal , which I personally dont like that much. Maybe you could add an option to change it or show me, where the styles for the editor are designed, so I can change it myself for my extension

Thanks a lot again, ive added a scrennshot to show what I mean

<img width="632" alt="Screenshot 2021-04-26 at 21 21 03" src="https://user-images.githubusercontent.com/77919093/116138676-68b6fe00-a6d5-11eb-930e-ce406742a561.png">

**Comment by simicd** [comment]
Hi @skriptum - thanks for your feedback, much appreciated! 

I was able to reproduce the color scheme you show in your screenshot. May you check your `Settings` -> `Text Editor Theme` and confirm whether the value is set to `jupyter`? I expect it's currently on `the-matrix`. 

Once it's set to `jupyter` the markdown editor should look just like the rest of the theme and work for both in light & dark mode:
![image](https://user-images.githubusercontent.com/10134699/116786731-91a60d00-aaa0-11eb-8cc9-5c737916d555.png)
![image](https://user-images.githubusercontent.com/10134699/116786860-4b04e280-aaa1-11eb-89e1-961614f69d84.png)
![image](https://user-images.githubusercontent.com/10134699/116786863-4dffd300-aaa1-11eb-9f9a-52264aaddb53.png)

**Comment by skriptum** [comment]
Oh yes, my bad, I didnt realize I changed this setting a long time ago. Finally, the Markdown editor looks really pretty now. Thanks again for the theme and your help 👍
