### ISSUE TITLE
Selecting Multiple Cells

### ISSUE THREAD

**Issue by beatslikeahelix** [simicd/jupyterlab-tailwind-theme#3]
I've encountered an issue where selecting multiple cells with the shift key doesn't work while the Tailwind themes are in use. I observe normal functionality using the default themes.

Thank you for these beautiful themes!

**Comment by simicd** [comment]
Great, thanks for reporting that bug as well! Also here I was able to reproduce it and fix for both the light and dark theme. I will commit release it together with the fix from issue #4.

![image](https://user-images.githubusercontent.com/10134699/73691928-a21bdc00-46d3-11ea-8be9-67ef60fbf756.png)
