### ISSUE TITLE
Tailwind Dark: Markdown Tables

### ISSUE THREAD

**Issue by beatslikeahelix** [simicd/jupyterlab-tailwind-theme#4]
While using Tailwind Dark, every second cell in a Markdown table is washed out:

<img width="124" alt="Tailwind Dark Markdown Table" src="https://user-images.githubusercontent.com/47506872/73277631-60c29280-41e2-11ea-9f79-aad99a39d655.png">

This behaviour is not observed in Tailwind Light:

<img width="117" alt="Tailwind Light Markdown Table" src="https://user-images.githubusercontent.com/47506872/73277606-56a09400-41e2-11ea-9baf-76c8b42127af.png">

Once again, thank you for these beautiful themes!

**Comment by simicd** [comment]
Hi @beatslikeahelix, I very much appreciate your feedback and glad you like the theme! I looked into the issue you reported and was able to reproduce it. I aligned the styles of pandas tables printed out with the Markdown table style. Below is a proposal, what do you think? 

![image](https://user-images.githubusercontent.com/10134699/73690182-181e4400-46d0-11ea-8914-bebde81de9d5.png)


![image](https://user-images.githubusercontent.com/10134699/73690066-db524d00-46cf-11ea-9ef4-34f3e5dc6125.png)

**Comment by beatslikeahelix** [comment]
Thank you very much indeed, both for this and resolving issue #3. The proposed changes look great champ!
