### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by BBassi** [simicd/jupyterlab-tailwind-theme#7]
![Screenshot 2020-05-04 at 10 09 46](https://user-images.githubusercontent.com/25634627/80951289-8a95e180-8def-11ea-9f84-bb414c12afea.png)

**Comment by simicd** [comment]
Hi @BBassi, thanks for reporting the error. I updated the dependencies so that on my machine the theme works with the new release 2.0 of JupyterLab. If you can confirm that you can install it as well I will close the issue.

**Comment by simicd** [comment]
Resolved
