### ISSUE TITLE
Using find to highlight text

### ISSUE THREAD

**Issue by hughcameron** [simicd/jupyterlab-tailwind-theme#9]
Great theme! I spotted that using find to highlight text is somewhat muted. 

![Screen Shot 2020-05-12 at 10 23 46 pm](https://user-images.githubusercontent.com/5008884/81691201-cab82c80-949f-11ea-980c-1df6917918e6.png)

By way of comparison, the vanilla JupyterLab theme shows the current match in yellow and other matches with an inverted white on black.

![Screen Shot 2020-05-12 at 10 23 21 pm](https://user-images.githubusercontent.com/5008884/81691214-cee44a00-949f-11ea-90b9-32c4260e0bf8.png)

Are there any tips to make the highlighting pop a bit more?

**Comment by simicd** [comment]
Hi @hughcameron, awesome glad to hear that! I appreciate you reported the flaw, what do you think of the following?

![image](https://user-images.githubusercontent.com/10134699/81737255-1ff04000-9498-11ea-875d-361fa9ffdb80.png)

![image](https://user-images.githubusercontent.com/10134699/81736931-a35d6180-9497-11ea-847e-06b3c682294f.png)

**Comment by hughcameron** [comment]
That looks great @simicd!

**Comment by simicd** [comment]
Great! I just published [v.0.4.1](https://www.npmjs.com/package/jupyterlab-tailwind-theme) to npm - will close this issue.
